[tool.black]
line-length = 80

[tool.ruff]
lint.select = [
    "E",   # pycodestyle (errors)s
    "F",   # pyflakes
    "W",   # pycodestyle (warnings)
    "I",   # isort (import sorting)
    "N",   # pep8-naming
    "UP",  # pyupgrade (modern syntax)
    "RET", # flake8-return (return statement style)
    "RUF", # Ruff-specific rules
    "B",   # flake8-bugbear (bug-prone patterns)
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
]

[tool.bandit]
skips = [
    "B101",
    "B404",
    "B603",
]
