#!/usr/bin/expect -f

## Change to 1 to see the output of tested commands
log_user 0

source ./tests/util.exp

spawn python3 -m src.analyse_cex -h

expect_exact "usage: analyse_cex.py \[-h\] \[--mtl MTL\] \[--de-bruijn DE_BRUIJN\] \[--model-checker {NUXMV,SPIN}\] \[--show-markings\] trace_file"
expect_exact ""
expect_exact "Determine the optimal weakening of an MTL formula to satisfy a given trace."
expect_exact ""
expect_exact "positional arguments:"
expect_exact "  trace_file            Path to the trace file to analyse. If not provided, stdin will be used."
expect_exact ""
expect_exact "options:"
expect_exact "  -h, --help            show this help message and exit"
expect_exact "  --mtl MTL             MTL specification"
expect_exact "  --de-bruijn DE_BRUIJN"
expect_exact "                        De Bruijn index of the subformula as a list of integers"
expect_exact "  --model-checker {NUXMV,SPIN}"
expect_exact "                        The model checker used (default: NUXMV)"
expect_exact "  --show-markings       Show the markings computed during analysis."
